.gitignore
.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package-lock.json
package.json

- init package json
- install husky
- setup husky pre-commit to run test and fix eslint errors
- setup husky to check commit msgs using lcommitLint
- check is-ci to not run script prepare

setup husky

---

.eslintrc.json
.gitignore
commitlint.config.js
package-lock.json
package.json
tsconfig.json

> The first is to create Folders, the second is then create files inside them.
```
- index.ts
- app.js
- test
- database.test.ts
- routes.test.ts
- middlewares
- index.ts
- routes
- index.ts
- controllers
- index.ts
- utils
- validation
- Customerr.ts
- jwt.ts
- index.ts
- database    
- models
- index.ts
- config
- build.sql
- build.ts
- connection.ts
- fakedata   
- index.ts
```

create folder and file structure for server

---

.eslintrc.json
package.json
test/routes.test.js

edit file structure remove test folder outside server folder

edit file structure

---

.eslintrc.json
client/.eslintrc.json
commitlint.config.js
package-lock.json
package.json
server/app.ts
server/database/config/build.sql
server/database/config/connection.ts
server/database/models/index.ts

Database Connection and configs

---

server/database/models/index.ts
server/database/models/user.ts

Create User Model 

---

server/database/models/gyms.ts
server/database/models/images.ts
server/database/models/index.ts

Create gym and image model in server

---

server/database/models/index.ts
server/database/models/reviews.ts
server/database/models/subscription.ts

create subscription and reviews model

---

server/utils/CustomError.ts
server/utils/index.ts

- Create a Class for it
- Have arguments `message`, `status`
```ts
class CustomError extends Error {
status: number;
constructor(message: string, status: number) {
super(message);
this.message = message;
this.status = status;
}
}
```
to use 
```ts
let statusCode = 500 // 4** || 5** ... ;
throw new CustomError('Your message', statusCode)
```

Create custom error for server

---

client/src/Components/Card/index.jsx
client/src/Components/Cards/index.jsx
client/src/Pages/HomePage.jsx
server/controllers/gyms/SerachGymByName.ts
server/controllers/gyms/index.ts
server/controllers/index.ts
server/routes/gyms.ts
server/utils/index.ts
test/routes.test.ts

-  Create route /api/v1/gyms/seach?q
-  Create controller
-  Handle data Form the database
and the response like this
```
[
{
id: 2,
gym_name: "Technogym gaza تكنو جيم",
logo: "https://bit.ly/3vrJEGt",
email: "techno.gym@gmail.com",
phone: "082621439",
city: "غزة",
description: "نادي رياضي يحتوي على ملعب صالة لكمال الاجسام ,بالضافة بها مسبح . أوقات الدوام من 8-12 صباحا ومن 12-16 مساء",
features: [
"مسبح",
"ميدان تنافسي",
"ملعب رياضي"
],
images: [
{
pathUrl: "https://bit.ly/3y0jWdK"
}
]
}
]
```

Create Api For Gym Search 

---

client/src/Components/GymProfile/index.jsx
client/src/Components/GymProfile/style.css
client/src/Pages/ProfileGym.jsx

Create gym profile main component

---

client/src/Components/GymImages/index.jsx
client/src/Components/GymImages/style.css
client/src/Components/GymProfile/index.jsx
client/src/Components/GymProfile/style.css
client/src/Pages/ProfileGym.jsx

Create Gym Images Component

---

package-lock.json
package.json
server/middleware/checkAuth.ts
server/middleware/index.ts
server/utils/index.ts
server/utils/jwt.ts
server/utils/types.ts

Create user/gym auth

---

.eslintrc.json
server/database/fakeData/index.ts

```js
await Promise.all([
...users.map(async (user: any) => {
await User.create(user);
}),
...gyms.map(async (gym: any) => {
await Gym.create(gym);
}),
]);
```
```js
await Promise.all([
...images.map(async (image: any) => {
await Image.create(image);
}),
...subscription.map(async (sub: any) => {
await Subscription.create(sub);
}),
...reviews.map(async (review: any) => {
await Review.create(review);
}),
]);
```
And remove subscriptions and reviews and images to another `Promise.all` block, to make sure to create them after creating users and gyms

Fix build database function to create data async

---

package-lock.json
package.json
server/utils/types.ts
server/utils/uplodeImage/index.ts

 [backend] Upload Image

---

client/src/App.js
client/src/Components/DashboardPageComponents/Header/index.jsx
client/src/Components/DashboardPageComponents/SideBar/index.jsx
client/src/Components/DashboardPageComponents/index.js
client/src/Components/index.js
client/src/Layouts/Dashboard.jsx
client/src/Pages/Gym.jsx
client/src/Pages/ReviewsGymPage.jsx
client/src/Pages/SubscriberGymPage.jsx
client/src/Pages/index.js

Front end Create layout dashboard

---

client/src/Components/LoginPage/index.js
client/src/Components/LoginPage/index.jsx
client/src/Components/index.js
client/src/Pages/LoginGym.jsx

Create Login page

---

client/src/App.js
client/src/Components/DashboardPage/UpdateProfile/index.jsx
client/src/Components/DashboardPage/UpdateProfile/style.css
client/src/Components/DashboardPage/index.js
client/src/Components/RegisterPage/Stepper/BodyStepper.jsx
client/src/Components/RegisterPage/Stepper/Steps/LoginInformation.jsx
client/src/Components/RegisterPage/Stepper/Steps/style.css
client/src/Components/index.js
client/src/Layouts/Dashboard.jsx
client/src/Pages/GymProfile.jsx
client/src/Pages/SingleGym.jsx
client/src/Pages/index.js
client/src/Services/genders.json
client/src/Services/index.js

**Empty Input**
**Full Input**
Validation Error

FrontEnd Create Page Update Profile Gym

---

server/controllers/gym/index.ts
server/controllers/gym/postImage.ts
server/controllers/index.ts
server/routes/gym.ts
server/routes/index.ts
server/utils/index.ts
server/utils/validation/gymImageSchema.ts
server/utils/validation/index.ts

Create API For Post Images Gym

---

client/src/Components/LoginPage/index.jsx
client/src/Components/RegisterPage/Stepper/Steps/DetailsComponent.jsx
client/src/Pages/LoginGym.jsx

Front End, Fix Login Page

---

client/src/Components/DashboardPage/Subscriptions/EnhancedTableHead.jsx
client/src/Components/DashboardPage/Subscriptions/EnhancedTableRow.jsx
client/src/Components/DashboardPage/Subscriptions/EnhancedTableToolbar.jsx
client/src/Components/DashboardPage/Subscriptions/index.jsx
client/src/Pages/SubscriberGymPage.jsx
client/src/Store/Services/index.js
client/src/Store/Services/subscription.js
client/src/Store/index.js

Create subscription table

---

client/src/Components/DashboardPage/Subscriptions/EnhancedTableRow.jsx

send request to update activate user status

[FrontEnd] handle activate user

---

client/src/App.js
client/src/Components/DashboardPage/Header/index.jsx
client/src/Components/DashboardPage/Header/style.css
client/src/Components/DashboardPage/SideBar/index.jsx
client/src/Components/DashboardPage/SideBar/style.css
client/src/Components/Layout/Navbar/style.css
client/src/Pages/NotFound.jsx
client/src/Pages/SingleGym.jsx
client/src/app.css

Not Found Page : 
Not Found Page  in dashboard 
Header 👍🏻 
and finally, active Link

Update header dashboard and update not found page

---

client/src/Components/SingleGym/GymReviews/index.jsx
client/src/Components/SingleGym/Modal/index.jsx
client/src/Pages/SingleGym.jsx

Send Request to Add Review.
Edit design review section.

Add review

---

server/controllers/auth/forgetPassword.ts
server/controllers/auth/index.ts
server/controllers/auth/resetPassword.ts
server/controllers/index.ts
server/routes/gyms.ts
server/utils/email/templates/forgetPasswordTemp.ts
server/utils/index.ts
server/utils/jwt.ts
server/utils/validation/forgetPasswordSchema.ts
server/utils/validation/gymLoginSchema.ts
server/utils/validation/gymRegisterSchema.ts
server/utils/validation/index.ts
server/utils/validation/resetPasswordSchema.ts

👍🏻  API one :
`/api/v1/gyms/reset/password`
> body request is
```json
{
"password": ".....",
"confirmPassword": ".....",
"token": "....."
}
``` 
👍🏻  API two :
`/api/v1/gyms/forget/password`
> body request is
```json
{
"email": "....."
}
```

Create Api forget password and reset it

---

client/src/App.js
client/src/Components/LoginPage/EmailInput.jsx
client/src/Components/LoginPage/ForgetPassword/index.jsx
client/src/Components/LoginPage/PasswordInput.jsx
client/src/Components/LoginPage/RestPassword/index.jsx
client/src/Components/LoginPage/index.jsx
client/src/Components/SingleGym/Modal/index.jsx
client/src/Pages/ForgetPassword.jsx
client/src/Pages/LoginGym.jsx
client/src/Pages/RestPassword.jsx

Forget password

---

client/src/Components/LoginPage/ForgetPassword/index.jsx
client/src/Components/LoginPage/index.jsx
client/src/Pages/ForgetPassword.jsx

Send Request to Forget Password.

Handle Forget password

---

client/src/Components/Layout/Footer/index.jsx
client/src/Layouts/Home.jsx
client/src/app.css

Fix footer style and put it in bottom

---

client/src/Components/DashboardPage/SideBar/index.jsx
client/src/Components/HomePage/Slider/Style.css
client/src/Components/SearchPage/CardResultFilter/Card.jsx
client/src/Components/SearchPage/CardResultFilter/index.jsx
server/database/fakeData/gyms.json
server/database/fakeData/images.json

Fix fack data in server
